# Generated by Django 5.2.17 on 2026-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
